version: '3.8'
services:
  ##### Python data generator
  data-generator:
    build: ./Data-generator
    container_name: data-generator
    depends_on:
      - broker
      - zookeeper
      - init-kafka
    
    networks:
      - backend
    environment:
      - KAFKA_BROKER=broker:${BROKER_INTERNAL_PORT}
  

  #### Kibana